### ISSUE TITLE
ACES DCTL NOT WORKING ON ANY IMAC

### ISSUE THREAD

**Issue by Amitcolorist** [baldavenger/ACES_DCTL#1]
Hi,
This ACES DCTL work fine on Mac tower but I dont now why its not working on any iMac.
Its may be because of gpu my tower have nvidia Gpu but iMac have radeon pro 580 same problem with all ofx also

**Comment by baldavenger** [comment]
The ACES DCTL set will only work with CUDA. OpenCL and Metal have limitations when it comes to inclusion files and overloading functions, which prevent them from reading and running the code.

With regards to the OFX Plugins, you'll need OpenCL only versions which you can download from here

https://github.com/baldavenger/Extras/blob/master/BaldavengerPluginsCL_no_cuda.zip

Make sure to select OpenCL and Manual in the GPU options in Preferences, otherwise Resolve might be running Metal by default (thereby preventing the plugins from working).

**Comment by hugohaddad** [comment]
Hi Paul, how are you?
I'm trying to work with DCTL and METAL and does not work for me. I did put your ACES and DCTLS files inside the folder but Davinci does not recognise it and still showing "NONE AVAILABLE" on DCTL List. The same for the Plugiins that I insert on OFX folder, my Davinci simple don't recognise it.

Do you have had some problems like this? Do you think the problem is with Metal or how can I fix it?
Thank you so much.

**Comment by baldavenger** [comment]
ACES DCTL are CUDA only. The OFX Plugins are CUDA only, except for a few older plugins which also work with OpenCL.

**Comment by baldavenger** [comment]
ACES DCTL now works with Metal.

https://github.com/baldavenger/Extras/blob/master/ACES_DCTL_NEW.zip

**Comment by hugohaddad** [comment]
Thank you so much Paul!

**Comment by Amitcolorist** [comment]
Thank you Paul
